#
# Azure Pipelines build steps common to all platforms.
#

steps:
- task: NodeTool@0
  inputs:
    versionSpec: 10.x
  displayName: Use Node.js 10

- script: yarn install
  displayName: Install dependencies

- script: yarn run tape:ci
  displayName: Run tests

- task: PublishTestResults@2
  inputs:
    testResultsFormat: JUnit
    testResultsFiles: test-results/tape.xml
    testRunTitle: Tests ($(Agent.OS))
  condition: succeededOrFailed()
  displayName: Publish test results
